---
- hosts: all
  vars:
  - ansible_python_interpreter: /usr/bin/python3 
  tasks:
  - name: Create a snapshot
    vmware_guest_disk:
        hostname: '10.215.99.55'                                         
        username: 'administrator@vsphere.local'
        password: 'Lab2021*'
        validate_certs: False
        datacenter: 'CURANSIBLEDCLAB01'
        name: 'LINUX01'
        disk:
          - size_gb: 2
            type: thin
            state: present
            scsi_controller: '0'
            unit_number: '1'
            scsi_type: 'paravirtual'
            datastore: 'Management'
           
