---
- name: creacion de VMS
  vmware_guest:
        hostname: '{{ vcenter }}'                                       # IP del vCenter
        username: '{{ vsphere_user }}'                        # Usuario de vCenter
        password: '{{ vsphere_password }}'                                           # Password de vCenter
        validate_certs: False
        name: "{{ Nombre_vm }}"                               # Nombre como se visualizar치 en el vCenter
        template: '{{ SO }}'                                           # Nombre de la Plantilla en el vCenterC
        datacenter: 'CURANSIBLEDCLAB01'                                # Nombre del Datacenter donde se va a desplegar
        cluster: 'Cluster_ansible'                                     # Nombre del Cluster donde se va a desplegar
        folder: '{{ FOLDER }}'                                       # Nombre del folder donde se va a desplegar
        annotation: 'Servidor desplegado desde Ansible AWX'            # Nota que se quiera colocar en el Servidor desplegado
        disk:
        - size_gb: '{{ DISK }}'                                        # Tama침o a asignar al disco
          type: thin                                                   # Formato del disco thin, thick o eagerzeroedthick 
          datastore: 'Management'                                      # Nombre del Datastore donde se va a desplegar
        hardware:
          memory_mb: '{{ RAM | int * 1024 }}'                         # Cantidad de Memoria RAM a asignar
          num_cpus: '{{ CPU }}'                                        # Cantidad de CPUs a asignar
          #num_cpu_cores_per_socket: 2                                  # Cantidad de CPUs Cores a asignar
          scsi: paravirtual
        networks:   
        - name: '{{ portgroup_name }}'                                   # Nombre de la Red a asignar
          ip: '{{ IP }}'                                               # Direcci칩n IP a asignar    
          netmask: '{{ MASK }}'                                        # Mascara de Red a asignar
          gateway: '{{ GW }}'                                          # Gateway a asignar
          dns_servers:                                                 # Direcci칩n (es) IP de los DNS a asignar
          - 8.8.8.8
          device_type: vmxnet3                                          #Tipo de Interfaz de Red a asignar
          start_connected: True
        customvalues:
        - key: "RemoteDisplay.maxConnections" 
          value: "3"
        - key: "isolation.tools.copy.disable"
          value: "True"
        - key: "isolation.tools.paste.disable"
          value: "True"
        - key: "isolation.tools.diskShrink.disable"
          value: "True"
        - key: "isolation.tools.diskWiper.disable"
          value: "True"
        - key: "mks.enabled"
          value: "False"
        - key: "tools.setInfo.sizeLimit"
          value: "1048576"
        - key: "RemoteDisplay.vnc.enabled"
          value: "False"
        - key: "tools.guestlib.enableHostInfo"
          value: "False"
        - key: "isolation.tools.dnd.disable" 
          value: "True"
        - key: "isolation.tools.setGUIOptions.enable"
          value: "True"
        - key: "isolation.device.connectable.disable"
          value: "True"	
        - key: "isolation.device.edit.disable"
          value: "True"   
        - key: "vmci0.unrestricted"
          value: "False"
        - key: "log.rotateSize"
          value: "1000000"
        - key: "log.keepOld"
          value: "10"
        - key: "guest.command.enabled"
          value: "False"
        - key: "tools.guestlib.enableHostInfo"
          value: "False"
        - key: "vcpu.hotadd"
          value: "True"
        - key: "mem.hotadd"
          value: "True"  
        - key: "devices.hotplug"
          value: "False"
        - key: "snapshot.redoNotWithParent"
          value: "True"
        state: poweredon                                               # Estado del Servidor luego del despliegue
        wait_for_ip_address: yes        
  delegate_to: localhost
  register: deploy
  with_items:                                # Cantidad de Servidores a crear (- 1 (crea un servidor), - 2 (crea dos servidores), etc)
     - '{{ SRV }}'
...  
