---
########################### TOMA EVIDENCIAS SERVIDORES LINUX ######################
# Elaborado por: SID - Implementacion
# Fecha: 19 de Abril de 2021
# Compañía: WCW
# Plataforma: LINUX
###################################################################################
  
    - name: nombre servidor - hostname
      shell: hostname > /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines

    - name: version y hostname - uname -a
      shell: uname -a >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines

    - name: discos df -h
      shell: df -h >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: discos -Total - lsblk |grep disk
      shell: lsblk |grep disk >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: Procesadors nproc
      shell: nproc >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
       
    - name: memory - free -m 
      shell: free -m >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: Uptime - uptime
      shell: uptime >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines

    #- name: date - timedatectl
    #  shell: timedatectl >> /tmp/Evidencias.txt
    #  register: out 
    #- debug: var=out.stdout_lines
                    
    - name: Ultimas actulizaciones - yum history
      shell: yum history >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: Messages Log - tail --lines=20 /var/log/messages
      shell: tail --lines=20 /var/log/messages >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    #- name: Servicio ejecutado - systemctl | grep running
    #  shell: systemctl | grep running >> /tmp/Evidencias.txt
    #  register: servicio
    #- debug: var=out.stdout_lines

    #- name: Susbsicripcion - subscription-manager list
     # shell: subscription-manager list
      #register: out
    #- debug: var=out.stdout_lines 
...
