---
# vars file for Create VMs ON Vmware
#########################################
###### Definicion Variables VMware ######
#########################################
# IP del vCenter donde se crearan las VMs
vcenter: '10.215.99.55'                         # IP del vCenter donde se crearan las VMs
vsphere_user: 'administrator@vsphere.local'     # Usuario con privilegios sobre vSphere para creacion de VMs
vsphere_password: 'Lab2021*'                    # Password de usuario de vSphere con privilegios para creacion de VMs
datacenter: 'CURANSIBLEDCLAB01'                 # Nombre del Datacenter dentro de vSphere en el cual seran alojadas las VMs.
cluster_name: 'Cluster_ansible'                 # Nombre del cluster donde quedaran las maquinas en el vCenter.
template: '{{ TEMPLATE_VAR }}'                          # Nombre de la plantilla cargada en el vCenter, desde la cual se crearan las VMs

####       Variables VMware MV       ####
#########################################
SRV:

# Variables VM numero 1 
  - name: VM1
    role: 'worker-server'                # Define el rol del servidor en la plataforma de VMware.
    vm_name: '{{ Nombre_vm }}'            # Variable que define el nombre de la VM en VMware.
    networks:   
        - name: '{{ portgroup_name }}'   
...
